<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="4" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-05T18:36:04 IST" name="Suite" finished-at="2025-05-05T18:36:29 IST" duration-ms="25221">
    <groups>
    </groups>
    <test started-at="2025-05-05T18:36:04 IST" name="Login with InValid" finished-at="2025-05-05T18:36:29 IST" duration-ms="25221">
      <class name="YaantracWeb.Tests.errorValidation">
        <test-method is-config="true" signature="LaunchAppication()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:04 IST" name="LaunchAppication" finished-at="2025-05-05T18:36:07 IST" duration-ms="2641" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchAppication -->
        <test-method signature="LoginInValidUserName(java.util.HashMap)[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:07 IST" name="LoginInValidUserName" data-provider="getData" finished-at="2025-05-05T18:36:11 IST" duration-ms="3677" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Demooo, userPassword=Demo@12345!}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginInValidUserName -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:11 IST" name="tearDown" finished-at="2025-05-05T18:36:11 IST" duration-ms="268" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="LaunchAppication()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:11 IST" name="LaunchAppication" finished-at="2025-05-05T18:36:13 IST" duration-ms="1809" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchAppication -->
        <test-method signature="LoginInValidUserName(java.util.HashMap)[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:13 IST" name="LoginInValidUserName" data-provider="getData" finished-at="2025-05-05T18:36:17 IST" duration-ms="3994" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{userName=Demoo, userPassword=Demo@1234567!}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginInValidUserName -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:17 IST" name="tearDown" finished-at="2025-05-05T18:36:17 IST" duration-ms="251" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="LaunchAppication()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:17 IST" name="LaunchAppication" finished-at="2025-05-05T18:36:19 IST" duration-ms="1923" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchAppication -->
        <test-method retried="true" signature="loginInvalid()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:19 IST" name="loginInvalid" finished-at="2025-05-05T18:36:23 IST" duration-ms="3765" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid Username or Password] but found [Inv@@alid Username or Password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid Username or Password] but found [Inv@@alid Username or Password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at YaantracWeb.Tests.errorValidation.loginInvalid(errorValidation.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginInvalid -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:23 IST" name="tearDown" finished-at="2025-05-05T18:36:23 IST" duration-ms="148" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="LaunchAppication()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:23 IST" name="LaunchAppication" finished-at="2025-05-05T18:36:25 IST" duration-ms="1851" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LaunchAppication -->
        <test-method signature="loginInvalid()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:25 IST" name="loginInvalid" finished-at="2025-05-05T18:36:29 IST" duration-ms="3997" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid Username or Password] but found [Inv@@alid Username or Password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid Username or Password] but found [Inv@@alid Username or Password]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at YaantracWeb.Tests.errorValidation.loginInvalid(errorValidation.java:44)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginInvalid -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:YaantracWeb.Tests.errorValidation@121bb45b]" started-at="2025-05-05T18:36:29 IST" name="tearDown" finished-at="2025-05-05T18:36:29 IST" duration-ms="258" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- YaantracWeb.Tests.errorValidation -->
    </test> <!-- Login with InValid -->
  </suite> <!-- Suite -->
</testng-results>
